# .streamlit/secrets.toml

[supabase]
url = "https://xulcbgjueznmiwxqsmky.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bGNiZ2p1ZXpubWl3eHFzbWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzUwMjUsImV4cCI6MjA3MjUxMTAyNX0.9z9cxCftdL4phYa7IyUuzgogsnNH6XMqHUZMX0t5_0U"